"""Update schema

Revision ID: ba3bbf7203dc
Revises: bd3dd4f619e6
Create Date: 2026-07-11 16:00:02.373204

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba3bbf7203dc'
down_revision: Union[str, Sequence[str], None] = 'bd3dd4f619e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('access_token', sa.String(), nullable=True))
    op.add_column('applications', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.drop_constraint('applications_job_id_fkey', 'applications', type_='foreignkey')
    op.drop_constraint('applications_user_id_fkey', 'applications', type_='foreignkey')
    op.create_foreign_key(None, 'applications', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'applications', 'jobs', ['job_id'], ['id'], ondelete='CASCADE')
    op.add_column('assessment_results', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.drop_constraint('assessment_results_application_id_fkey', 'assessment_results', type_='foreignkey')
    op.create_foreign_key(None, 'assessment_results', 'applications', ['application_id'], ['id'], ondelete='CASCADE')
    op.add_column('assessments', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.drop_constraint('assessments_job_id_fkey', 'assessments', type_='foreignkey')
    op.create_foreign_key(None, 'assessments', 'jobs', ['job_id'], ['id'], ondelete='CASCADE')
    op.add_column('candidate_profiles', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.drop_constraint('candidate_profiles_user_id_fkey', 'candidate_profiles', type_='foreignkey')
    op.create_foreign_key(None, 'candidate_profiles', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.add_column('companies', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('jobs', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.drop_constraint('jobs_owner_id_fkey', 'jobs', type_='foreignkey')
    op.create_foreign_key(None, 'jobs', 'users', ['owner_id'], ['id'], ondelete='CASCADE')
    op.add_column('users', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.drop_constraint('users_company_id_fkey', 'users', type_='foreignkey')
    op.create_foreign_key(None, 'users', 'companies', ['company_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_foreign_key('users_company_id_fkey', 'users', 'companies', ['company_id'], ['id'])
    op.drop_column('users', 'updated_at')
    op.drop_constraint(None, 'jobs', type_='foreignkey')
    op.create_foreign_key('jobs_owner_id_fkey', 'jobs', 'users', ['owner_id'], ['id'])
    op.drop_column('jobs', 'updated_at')
    op.drop_column('companies', 'updated_at')
    op.drop_constraint(None, 'candidate_profiles', type_='foreignkey')
    op.create_foreign_key('candidate_profiles_user_id_fkey', 'candidate_profiles', 'users', ['user_id'], ['id'])
    op.drop_column('candidate_profiles', 'updated_at')
    op.drop_constraint(None, 'assessments', type_='foreignkey')
    op.create_foreign_key('assessments_job_id_fkey', 'assessments', 'jobs', ['job_id'], ['id'])
    op.drop_column('assessments', 'updated_at')
    op.drop_constraint(None, 'assessment_results', type_='foreignkey')
    op.create_foreign_key('assessment_results_application_id_fkey', 'assessment_results', 'applications', ['application_id'], ['id'])
    op.drop_column('assessment_results', 'updated_at')
    op.drop_constraint(None, 'applications', type_='foreignkey')
    op.drop_constraint(None, 'applications', type_='foreignkey')
    op.create_foreign_key('applications_user_id_fkey', 'applications', 'users', ['user_id'], ['id'])
    op.create_foreign_key('applications_job_id_fkey', 'applications', 'jobs', ['job_id'], ['id'])
    op.drop_column('applications', 'updated_at')
    op.drop_column('applications', 'access_token')
    # ### end Alembic commands ###
