'use client';

import { useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { 
  Briefcase,
  MapPin,
  Banknote,
  Globe,
  Clock,
  Target,
  Zap,
  ShieldCheck,
  ArrowRight,
  ArrowLeft,
  Sparkles,
  CheckCircle2,
  Aperture,
  Loader2
} from 'lucide-react';
import { useRouter } from 'next/navigation';
import { api } from '@/lib/api';
import Link from 'next/link';

export default function NewJobWizard() {
  const router = useRouter();
  const [step, setStep] = useState(1);
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [error, setError] = useState('');

  const [formData, setFormData] = useState({
    title: '',
    language: 'English',
    location: '',
    salary_range: '',
    job_type: 'Full-time',
    expected_outcomes: '',
    specific_skills: '',
    compliance_criteria: '',
  });

  const handleChange = (e: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement | HTMLSelectElement>) => {
    setFormData(prev => ({ ...prev, [e.target.name]: e.target.value }));
  };

  const nextStep = () => {
    setError('');
    // Basic validation per step
    if (step === 1) {
      if (!formData.title || !formData.location || !formData.salary_range) {
        setError('Please fill in all required fields.');
        return;
      }
    }
    if (step === 2) {
      if (!formData.expected_outcomes || !formData.specific_skills || !formData.compliance_criteria) {
        setError('Please define the AI simulation parameters.');
        return;
      }
    }
    setStep(s => s + 1);
  };

  const prevStep = () => setStep(s => s - 1);

  const handleSubmit = async () => {
    setIsSubmitting(true);
    setError('');
    try {
      const payload = {
        ...formData,
        description: 'Autogenerated by AI Proctoring Engine'
      };
      const newJob = await api.post('/jobs', payload);
      router.push(`/recruiter/jobs/${newJob.id}`);
    } catch (err: any) {
      setError(err.message);
      setIsSubmitting(false);
    }
  };

  const steps = [
    { num: 1, title: 'Role Overview' },
    { num: 2, title: 'AI Parameters' },
    { num: 3, title: 'Review & Deploy' }
  ];

  return (
    <div className="max-w-4xl mx-auto space-y-8">
      {/* Header */}
      <div className="flex items-start justify-between">
        <div>
          <Link href="/recruiter/jobs" className="inline-flex items-center gap-2 text-sm font-medium text-brand-gray-dark hover:text-brand-secondary transition-colors mb-4">
            <ArrowLeft className="w-4 h-4" />
            Back to Active Roles
          </Link>
          <h1 className="text-3xl font-display font-bold text-brand-secondary tracking-tight flex items-center gap-3">
            Program New Assessment
            <span className="px-2.5 py-1 rounded-md bg-brand-primary/20 text-brand-primary text-[10px] font-bold uppercase tracking-widest border border-brand-primary/30">Wizard</span>
          </h1>
          <p className="text-brand-gray-dark mt-2">Configure parameters for the AI evaluator engine.</p>
        </div>
      </div>

      {/* Stepper */}
      <div className="bg-brand-white p-4 rounded-2xl border border-brand-gray-light/30 shadow-sm flex items-center justify-between relative overflow-hidden">
        <div className="absolute top-1/2 left-0 w-full h-0.5 bg-brand-gray-light/30 -translate-y-1/2 z-0" />
        <div className="absolute top-1/2 left-0 h-0.5 bg-brand-primary -translate-y-1/2 transition-all duration-500 z-0" style={{ width: `${((step - 1) / 2) * 100}%` }} />
        
        {steps.map(s => (
          <div key={s.num} className="relative z-10 flex flex-col items-center gap-2 bg-brand-white px-4">
            <div className={`w-10 h-10 rounded-xl flex items-center justify-center font-bold text-sm transition-colors border-2 ${
              step > s.num 
                ? 'bg-brand-primary border-brand-primary text-brand-white'
                : step === s.num
                  ? 'bg-brand-secondary border-brand-secondary text-brand-white'
                  : 'bg-brand-white border-brand-gray-light/50 text-brand-gray-light'
            }`}>
              {step > s.num ? <CheckCircle2 className="w-5 h-5" /> : s.num}
            </div>
            <span className={`text-xs font-bold uppercase tracking-wider ${step >= s.num ? 'text-brand-secondary' : 'text-brand-gray-light'}`}>
              {s.title}
            </span>
          </div>
        ))}
      </div>

      {error && (
        <div className="bg-red-50 text-red-700 text-sm p-4 rounded-xl border border-red-200 font-medium flex items-center gap-3 shadow-sm">
          <ShieldCheck className="w-5 h-5" />
          {error}
        </div>
      )}

      {/* Wizard Content */}
      <div className="bg-brand-white rounded-2xl border border-brand-gray-light/30 shadow-sm overflow-hidden relative">
        <div className="absolute top-0 right-0 w-64 h-64 bg-brand-primary/5 rounded-full blur-3xl -mr-20 -mt-20 pointer-events-none" />
        
        <div className="p-8">
          <AnimatePresence mode="wait">
            
            {/* STEP 1 */}
            {step === 1 && (
              <motion.div
                key="step1"
                initial={{ opacity: 0, x: 20 }}
                animate={{ opacity: 1, x: 0 }}
                exit={{ opacity: 0, x: -20 }}
                transition={{ duration: 0.3 }}
                className="space-y-6"
              >
                <h2 className="text-xl font-display font-bold text-brand-secondary flex items-center gap-2 mb-6">
                  <Briefcase className="w-5 h-5 text-brand-primary" />
                  Role Specifications
                </h2>
                <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                  <div className="col-span-1 md:col-span-2">
                    <label className="block text-sm font-bold text-brand-secondary mb-2">Job Title</label>
                    <input 
                      name="title" value={formData.title} onChange={handleChange}
                      placeholder="e.g. Senior Backend Engineer"
                      className="w-full bg-transparent border border-brand-gray-light rounded-xl px-4 py-3 text-brand-secondary focus:outline-none focus:ring-2 focus:ring-brand-primary transition-colors text-sm font-medium"
                    />
                  </div>
                  <div>
                    <label className="block text-sm font-bold text-brand-secondary mb-2 flex items-center gap-1.5"><MapPin className="w-4 h-4 text-brand-gray-dark" /> Location</label>
                    <input 
                      name="location" value={formData.location} onChange={handleChange}
                      placeholder="e.g. Remote / Jakarta"
                      className="w-full bg-transparent border border-brand-gray-light rounded-xl px-4 py-3 text-brand-secondary focus:outline-none focus:ring-2 focus:ring-brand-primary transition-colors text-sm font-medium"
                    />
                  </div>
                  <div>
                    <label className="block text-sm font-bold text-brand-secondary mb-2 flex items-center gap-1.5"><Banknote className="w-4 h-4 text-brand-gray-dark" /> Salary Range</label>
                    <input 
                      name="salary_range" value={formData.salary_range} onChange={handleChange}
                      placeholder="e.g. Rp 15M - 25M"
                      className="w-full bg-transparent border border-brand-gray-light rounded-xl px-4 py-3 text-brand-secondary focus:outline-none focus:ring-2 focus:ring-brand-primary transition-colors text-sm font-medium"
                    />
                  </div>
                  <div>
                    <label className="block text-sm font-bold text-brand-secondary mb-2 flex items-center gap-1.5"><Globe className="w-4 h-4 text-brand-gray-dark" /> Interview Language</label>
                    <select 
                      name="language" value={formData.language} onChange={handleChange}
                      className="w-full bg-transparent border border-brand-gray-light rounded-xl px-4 py-3 text-brand-secondary focus:outline-none focus:ring-2 focus:ring-brand-primary transition-colors text-sm font-medium"
                    >
                      <option value="English">English</option>
                      <option value="Indonesian">Indonesian</option>
                    </select>
                  </div>
                  <div>
                    <label className="block text-sm font-bold text-brand-secondary mb-2 flex items-center gap-1.5"><Clock className="w-4 h-4 text-brand-gray-dark" /> Job Type</label>
                    <select 
                      name="job_type" value={formData.job_type} onChange={handleChange}
                      className="w-full bg-transparent border border-brand-gray-light rounded-xl px-4 py-3 text-brand-secondary focus:outline-none focus:ring-2 focus:ring-brand-primary transition-colors text-sm font-medium"
                    >
                      <option value="Full-time">Full-time</option>
                      <option value="Contract">Contract</option>
                      <option value="Internship">Internship</option>
                    </select>
                  </div>
                </div>
              </motion.div>
            )}

            {/* STEP 2 */}
            {step === 2 && (
              <motion.div
                key="step2"
                initial={{ opacity: 0, x: 20 }}
                animate={{ opacity: 1, x: 0 }}
                exit={{ opacity: 0, x: -20 }}
                transition={{ duration: 0.3 }}
                className="space-y-6"
              >
                <div className="mb-6">
                  <h2 className="text-xl font-display font-bold text-brand-secondary flex items-center gap-2 mb-2">
                    <Aperture className="w-5 h-5 text-brand-accent" />
                    AI Evaluator Parameters
                  </h2>
                  <p className="text-sm text-brand-gray-dark">Instruct the AI on exactly what to measure during the Micro-Interview.</p>
                </div>
                
                <div className="space-y-5">
                  <div className="bg-brand-gray-light/10 p-5 rounded-2xl border border-brand-gray-light/30">
                    <label className="block text-sm font-bold text-brand-secondary mb-2 flex items-center gap-2">
                      <Target className="w-4 h-4 text-brand-primary" />
                      Expected Outcomes (6-12 Months)
                    </label>
                    <p className="text-xs text-brand-gray-dark mb-3">What must they achieve? The AI will test if they have a realistic plan.</p>
                    <textarea 
                      name="expected_outcomes" value={formData.expected_outcomes} onChange={handleChange}
                      rows={3}
                      placeholder="e.g. Migrate the monolith to microservices within 6 months while maintaining 99.9% uptime."
                      className="w-full bg-white border border-brand-gray-light rounded-xl px-4 py-3 text-brand-secondary focus:outline-none focus:ring-2 focus:ring-brand-primary transition-colors text-sm font-medium resize-none shadow-sm"
                    />
                  </div>

                  <div className="bg-brand-gray-light/10 p-5 rounded-2xl border border-brand-gray-light/30">
                    <label className="block text-sm font-bold text-brand-secondary mb-2 flex items-center gap-2">
                      <Zap className="w-4 h-4 text-brand-accent" />
                      Specific Skills (Non-Trainable)
                    </label>
                    <p className="text-xs text-brand-gray-dark mb-3">Skills they MUST possess on day one.</p>
                    <textarea 
                      name="specific_skills" value={formData.specific_skills} onChange={handleChange}
                      rows={3}
                      placeholder="e.g. Expert-level Go, Kubernetes orchestration, and PostgreSQL performance tuning."
                      className="w-full bg-white border border-brand-gray-light rounded-xl px-4 py-3 text-brand-secondary focus:outline-none focus:ring-2 focus:ring-brand-primary transition-colors text-sm font-medium resize-none shadow-sm"
                    />
                  </div>

                  <div className="bg-brand-gray-light/10 p-5 rounded-2xl border border-brand-gray-light/30">
                    <label className="block text-sm font-bold text-brand-secondary mb-2 flex items-center gap-2">
                      <ShieldCheck className="w-4 h-4 text-red-500" />
                      Compliance & Red Flags
                    </label>
                    <p className="text-xs text-brand-gray-dark mb-3">What should immediately disqualify them?</p>
                    <textarea 
                      name="compliance_criteria" value={formData.compliance_criteria} onChange={handleChange}
                      rows={3}
                      placeholder="e.g. Lack of security-first mindset, unable to explain basic ACID properties."
                      className="w-full bg-white border border-brand-gray-light rounded-xl px-4 py-3 text-brand-secondary focus:outline-none focus:ring-2 focus:ring-brand-primary transition-colors text-sm font-medium resize-none shadow-sm"
                    />
                  </div>
                </div>
              </motion.div>
            )}

            {/* STEP 3 */}
            {step === 3 && (
              <motion.div
                key="step3"
                initial={{ opacity: 0, x: 20 }}
                animate={{ opacity: 1, x: 0 }}
                exit={{ opacity: 0, x: -20 }}
                transition={{ duration: 0.3 }}
                className="space-y-6"
              >
                <div className="text-center py-6">
                  <div className="w-16 h-16 bg-brand-primary/20 text-brand-primary rounded-full flex items-center justify-center mx-auto mb-4">
                    <Sparkles className="w-8 h-8" />
                  </div>
                  <h2 className="text-2xl font-display font-bold text-brand-secondary mb-2">Ready to Deploy</h2>
                  <p className="text-sm text-brand-gray-dark max-w-md mx-auto">
                    Review the role details below. Upon generating, the AI engine will construct a dynamic scenario specifically for this position.
                  </p>
                </div>

                <div className="bg-[#F7F9F9] rounded-xl border border-brand-gray-light/50 p-6 space-y-4">
                  <div className="grid grid-cols-2 gap-4 text-sm">
                    <div>
                      <span className="block text-brand-gray-dark text-xs uppercase font-bold mb-1">Title</span>
                      <span className="font-bold text-brand-secondary">{formData.title}</span>
                    </div>
                    <div>
                      <span className="block text-brand-gray-dark text-xs uppercase font-bold mb-1">Location & Type</span>
                      <span className="font-bold text-brand-secondary">{formData.location} • {formData.job_type}</span>
                    </div>
                  </div>
                  <div className="pt-4 border-t border-brand-gray-light/30">
                    <span className="block text-brand-gray-dark text-xs uppercase font-bold mb-1">Core Requirement</span>
                    <span className="font-medium text-brand-secondary text-sm">{formData.expected_outcomes.substring(0, 100)}...</span>
                  </div>
                </div>
              </motion.div>
            )}

          </AnimatePresence>
        </div>

        {/* Footer Actions */}
        <div className="p-6 bg-brand-gray-light/5 border-t border-brand-gray-light/30 flex items-center justify-between">
          <button 
            type="button" 
            onClick={step === 1 ? () => router.back() : prevStep}
            className="px-6 py-2.5 rounded-lg font-bold text-brand-gray-dark hover:text-brand-secondary hover:bg-brand-gray-light/20 transition-colors text-sm"
          >
            {step === 1 ? 'Cancel' : 'Back'}
          </button>

          {step < 3 ? (
            <button 
              type="button" 
              onClick={nextStep}
              className="px-6 py-2.5 rounded-lg font-bold bg-brand-secondary hover:bg-brand-dark-teal text-brand-white transition-all flex items-center gap-2 text-sm shadow-sm"
            >
              Continue
              <ArrowRight className="w-4 h-4" />
            </button>
          ) : (
            <button 
              type="button" 
              onClick={handleSubmit}
              disabled={isSubmitting}
              className="px-8 py-3 rounded-lg font-bold bg-brand-primary hover:bg-brand-dark-teal text-brand-white transition-all flex items-center gap-2 text-sm shadow-md disabled:opacity-50"
            >
              {isSubmitting ? (
                <><Loader2 className="w-4 h-4 animate-spin" /> Deploying...</>
              ) : (
                <><Aperture className="w-4 h-4" /> Generate AI Assessment</>
              )}
            </button>
          )}
        </div>
      </div>
    </div>
  );
}
